#!/usr/bin/env bash

set -x
set -euo pipefail

contain() {
  declare -n array="$1"
  declare val="$2"

  for elem in "${array[@]}"; do
    if [[ "$elem" == "$val" ]]; then
      return 0
    fi
  done

  return 1
}

read-config() {
  local expected_keys="$1"
  local config_file="$2"

  while read -r line; do
    # shellcheck disable=SC2034
    local value="${line#*=}"
    local key="${line%%=*}"

    if contain "$expected_keys" "$key"; then
      eval "declare -g $key=$value"
    else
      echo >&2 "Unrecognized key: $key"
    fi
  done <"$config_file"
}

#shellcheck disable=SC2034
keys=(LOCATION)

read-config keys conf
echo "$LOCATION"
