#!/usr/bin/env bash

set -euo pipefail

dpkg --add-architecture i386
apt update
apt install -y curl lib32gcc1 lib32stdc++6 libcurl4-gnutls-dev:i386

(
[[ -d ~/steam ]] || mkdir ~/steam
cd ~ || exit
curl -sqL "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz" | tar -xzf - -C steam
)
